### ISSUE TITLE
Switch Not Turning On

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#93] opened 2017-02-07 03:23 UTC
Just noticed that one wall switch (non-dimmer) is receiving a command to turn off for both on and off commands from Homekit. This is my only non-dimmer wall switch. The other dimmer switches are properly turning on and off.

**Comment by reallybman** [comment] 2017-02-07 18:23
Not same issue as #94. Everything works except this one non-dimmer wall switch. Vera is receiving a turn off command for both on and off.

**Comment by drewcovi** [comment] 2017-02-07 18:34
I believe the root of the issue is the same. But #94 was marked as a dupe of this issue. Not the other way around. So this should hopefully get fixed with a hotfix just pushed to *master.* 

I'll have to test tonight though.

**Comment by reallybman** [comment] 2017-02-07 22:13
@drewcovi I tested the fix and it works! Nice job.

**Comment by bjestavs** [comment] 2017-02-07 23:53
doesn´t seem to work for me. I also saw a this message when I started homebridge
"Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'."

I don´t know if it anything to do with my problem.

**Comment by drewcovi** [comment] 2017-02-08 02:29
@bjestavs yeah that's almost certainly something in your setup.

**Comment by drewcovi** [comment] 2017-02-08 04:42
closing as per comments by @reallybman

**Closed by drewcovi** 2017-02-08 04:42 UTC

**Comment by reallybman** [comment] 2017-02-09 18:49
So - back to this again. The physical switch within homekit works to turn switch on and off, but Siri seems to be sending an "off" command to Vera even when asking her to turn the switch on. Maybe that is a Siri bug? All other lights, locks and switches are working in my setup with Siri.
