### ISSUE TITLE
Dimmer Percentages

### ISSUE THREAD

**Issue by erpeters3** [damianxd/homebridge-vera#48] opened 2016-10-16 18:36 UTC
When I set dinners to a percentage with a Scene, they very shortly jump up to 100%. Any ideas?

**Comment by drewcovi** [comment] 2016-10-17 14:19
This is probably a dupe of #25

**Comment by pattont** [comment] 2016-12-23 07:01
I'm having the same issue. Updated my Homebridge Vera Plugin and am running UI7. My dimmer is on a fan and when I set the fan to 50% in a scene it jumps straight to 100%, but the UI still shows 50%.

**Closed** 2017-01-21 18:06 UTC
