### ISSUE TITLE
433-Switches not turning on and scenes not working in Siri

### ISSUE THREAD

**Issue by bjestavs** [damianxd/homebridge-vera#94] opened 2017-02-07 15:27 UTC
I installed homebridge-Vera through this [link](https://docs.google.com/document/d/1X6zpaE-FTld09kEHmTlrX-4KTC71TbvtbIlYbrFysvc/edit) a couple of months ago and all went well. When I now try to reinstall my RPi3B with the same instructions it´s not working at all. I have a Vera Edge connected to a RFXTRX433E. All my wall plugs are Nexa self learning. Everything works well from Vera UI but with with my iPhone I get the following errors:

- I can turn off switches through Apple Home, but not on. Works the same way with Siri.
- I can control my scenes through buttons in Home, but not with Siri (I get a respons that sais Siri can´t do this. I have swedish language so I don´t know what the english respons would be).

Great service when it worked though.

**Comment by drewcovi** [comment] 2017-02-07 16:36
Will reopen if not a dupe of #93

**Closed by drewcovi** 2017-02-07 16:36 UTC
Labels: duplicate
